### ISSUE TITLE
File Watcher

### ISSUE THREAD

**Issue by exbit** [swordev/phpstan-vscode#2]
When the option - "Phpstan: File Watcher = true" is set, your extension starts analysis of all project files - this creates a load and takes a lot of time.
Is it possible to run the analysis of either only the file being changed or use the cache to speed up the analysis?

**Comment by juanrgm** [comment]
Hi,

> When the option - "Phpstan: File Watcher = true" is set, your extension starts analysis of all project files - this creates a load and takes a lot of time.

The first analysis can be slower because the cache is empty and it requires scan all files.

> Is it possible to run the analysis of either only the file being changed or use the cache to speed up the analysis?

The extension only runs the analysis when it changes a file that it matches with the phpstan [config](https://phpstan.org/config-reference#multiple-files) (`parameters.paths`, `parameters.fileExtensions`).

PHPStan already has a [file cache system](https://phpstan.org/config-reference#caching) for speed up the analysis.

How many files are you analysing? The `parameters.excludes_analyse` config is not yet supported.

**Comment by exbit** [comment]
My **phpstan.neon**
`includes:
    - ./vendor/nunomaduro/larastan/extension.neon

parameters:
    paths:
        - app
        - config
        - database
        - nova-components
        - resources
        - routes
        - tests

    # The level 8 is the highest level
    level: 1

    ignoreErrors:
    - '#Call to an undefined static method Illuminate\\Support\\Facades\\DB::rollback\(\).#'
    -
        message: '#Call to an undefined method Illuminate\\Support\\Fluent::on\(\).#'
        path: ./database/migrations/*
    -
        # Undefined property resources
        message: '#Access to an undefined property App\\Nova\\Resources[\\a-zA-Z]+Resource::\$[a-z\_]+.#'
        path: ./app/Nova/Resources/*
    -
        # Undefined property models
        message: '#Access to an undefined property App\\Models\\[a-zA-Z]+::\$[a-z\_]+.#'
        path: ./app/Models/*

    excludes_analyse:
        - vendor

    checkMissingIterableValueType: true`

when changing one file, analysis of all files is always started. My log:
`# Command: analyse
Note: Using configuration file phpstan.neon.

   0/215 [>---------------------------]   0%

[2K  40/215 [=====>----------------------]  18%

[2K  60/215 [=======>--------------------]  27%

[2K  80/215 [==========>-----------------]  37%

[2K 100/215 [=============>--------------]  46%

[2K 120/215 [===============>------------]  55%

[2K 140/215 [==================>---------]  65%

[2K 160/215 [====================>-------]  74%

[2K 180/215 [=======================>----]  83%

[2K 195/215 [=========================>--]  90%

[2K 215/215 [============================] 100%



{"totals":{"errors":1,"file_errors":0},"files":[],"errors":["Ignored error pattern #Call to an undefined method Illuminate\\\\Support\\\\Fluent::on\\(\\).# in path database\\migrations\\* was not matched in reported errors."]}`

**Comment by juanrgm** [comment]
When there is a fatal error in any file PHPStan does not update the cache so always it analyzes all files, but this does not seem to be your case.

215 files are few for PHPStan and it should run fast since I work in projects with with +1000 files and the PHPStan cache works correctly. You can try to check if it exists% tmp% \ phpstan \ resultCache.php and execute PHPStan: clear cache in VSCode.

Remember this extension is only a PHPStan wrapper for runs the analyze command and this case seems to be a direct problem with the PHPStan cache.
