### ISSUE TITLE
Hello !

### ISSUE THREAD

**Issue by palansher** [swordev/phpstan-vscode#3]
Unfortunately, doesn't work from VS Code:

```
# Config:
{
  "parameters": {
    "excludePaths": [
      "vendor/*"
    ],
    "bootstrapFiles": [
      "include/config_app.php"
    ],
    "scanDirectories": [
      "."
    ],
    "fileExtensions": [
      "php"
    ]
  }
}
# Command: analyse
Note: Using configuration file /home/vladp/dev/sites/gt-vladp-dev1/phpstan.neon.

At least one path must be specified to analyse.

# Spawn error
Unexpected end of JSON input

```

But works well from the command line.

```
09:15 $ vendor/bin/phpstan -V
PHPStan - PHP Static Analysis Tool 0.12.68
  ~/dev/sites/gt-vladp-dev1 [develop ↑·1|✚ 1] 
```

**Comment by juanrgm** [comment]
Hi palansher,

> At least one path must be specified to analyse.

That warning is generated by PHPStan and it is saying you that `paths` parameter is required (https://phpstan.org/config-reference#neon-format).

> But works well from the command line.
>    09:15 $ vendor/bin/phpstan -V
>    PHPStan - PHP Static Analysis Tool 0.12.68
>    ~/dev/sites/gt-vladp-dev1 [develop ↑·1|✚ 1] 

It works because you are not passing the `analyse` argument, if you execute `phpstan analyse`, you will get the same result: `At least one path must be specified to analyse`.

**Comment by palansher** [comment]
Thank you so much!
